version: "3"
services:
  steam_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - <port_on_host>:8000 # TODO: change to your port on host
    restart: always
    environment:
      - DATABASE_ENGINE=mysql
      - DATABASE_NAME=steam
      - DATABASE_USER=root
      - DATABASE_PASSWORD=steam
      - DATABASE_HOST=steam_mysql
      - DATABASE_PORT=3306
      - REDIS_HOST=steam_redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=""
      - REDIS_PASSWORD=""
      - EMAIL_HOST=smtp.gmail.com # TODO: change to your email host
      - EMAIL_PORT=587 # TODO: change to your email port
      - EMAIL_HOST_USER="" # TODO: change to your email host user
      - EMAIL_HOST_PASSWORD="" # TODO: change to your email host password
      - BETTERSTACK_LOG_TOKEN=dXECcUYZxNVLX5GHN8XyRhzt
      - BETTERSTACK_LOG_HOST=s1529184.eu-nbg-2.betterstackdata.com
    volumes:
      - <path_on_host>/steam:/usr/src/app/media # TODO: change to your media path
    depends_on:
      - steam_mysql
      - steam_redis

  steam_mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "steam"
      MYSQL_ROOT_PASSWORD: "steam"
    ports:
      - <port_on_host>:3306 # TODO: change to your port on host
    volumes:
      - mysql_data:/var/lib/mysql # TODO: change to your mysql data path

  steam_redis:
    image: redis:6.0
    restart: always
    ports:
      - <port_on_host>:6379 # TODO: change to your port on host
    volumes:
      - redis_data:/data # TODO: change to your redis data path

volumes:
  mysql_data:
  redis_data: